model_checkpoint:
    monitor: "Validation loss"
    save_top_k: 1
    save_last: True
    mode: "min"
    verbose: False
    dirpath: 'checkpoints/'
    filename: '{epoch:02d}'
    every_n_epochs: 1
    save_on_train_epoch_end: False
    