data_dir: ${data_dir}
batch_size: 16
image_width: 224
image_height: 224
seed: 9290
valid_size: 0.2
num_workers: 4
shuffle: True
cifar10_normalize_inputs: True
data_augmentations: "basic" # 'none', 'basic' 'extra'
transforms_type: 'default' # 'defaul', 'custom', 'anomaly'
